# -*- coding:utf-8 -*-
# http://projecteuler.net/problem=29
# How many distinct terms are in the sequence generated by a**b for 
# 2 < a < 100 and 2 < b < 100?
from time import time

# Let's use a map which keys are the a**b values. Could have been done
# with a simple set too.
start_t = time()
map = {}
for a in range(2, 101):
	for b in range(2, 101):
		map[a**b] = 1
end_t = time()
print "Answer to problem 29 is %s" % len(map)
print "Took %s" % (end_t - start_t)
